# Local (non-Docker) development profile.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sentinel}
spring.datasource.username=${DB_USERNAME:sentinel}
spring.datasource.password=${DB_PASSWORD:sentinel_dev_pw}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.pool-name=sentinel-cp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.meridiantrust.sentinel=DEBUG
