-- ===========================================================================
-- Sentinel AML - core schema
-- Portable DDL: validated against PostgreSQL 16 and H2 2.x (PostgreSQL mode).
-- Relationship chain: customer -> account -> transaction -> alert -> case
-- ===========================================================================

CREATE TABLE customers (
    customer_id             VARCHAR(32)  PRIMARY KEY,
    first_name              VARCHAR(80)  NOT NULL,
    last_name               VARCHAR(80)  NOT NULL,
    gender                  VARCHAR(8),
    date_of_birth           DATE,
    email                   VARCHAR(160),
    phone_number            VARCHAR(32),
    national_id             VARCHAR(32),
    city                    VARCHAR(80),
    state                   VARCHAR(80),
    country                 VARCHAR(2)   NOT NULL DEFAULT 'IN',
    postal_code             VARCHAR(16),
    occupation              VARCHAR(80),
    annual_income           NUMERIC(18,2),
    marital_status          VARCHAR(24),
    education_level         VARCHAR(40),
    employment_status       VARCHAR(40),
    customer_since          DATE,
    customer_segment        VARCHAR(24),
    kyc_status              VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    risk_rating             VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    is_politically_exposed  BOOLEAN      NOT NULL DEFAULT FALSE,
    preferred_channel       VARCHAR(40),
    email_verified          BOOLEAN      NOT NULL DEFAULT FALSE,
    phone_verified          BOOLEAN      NOT NULL DEFAULT FALSE,
    num_complaints_last_year INTEGER     NOT NULL DEFAULT 0,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cust_risk    ON customers (risk_rating);
CREATE INDEX idx_cust_country ON customers (country);

CREATE TABLE accounts (
    account_id              VARCHAR(32)  PRIMARY KEY,
    customer_id             VARCHAR(32)  NOT NULL REFERENCES customers (customer_id),
    account_type            VARCHAR(24)  NOT NULL,
    account_status          VARCHAR(24)  NOT NULL DEFAULT 'ACTIVE',
    currency                VARCHAR(3)   NOT NULL DEFAULT 'INR',
    open_date               DATE,
    close_date              DATE,
    branch_code             VARCHAR(16),
    branch_city             VARCHAR(80),
    current_balance         NUMERIC(18,2) NOT NULL DEFAULT 0,
    avg_monthly_balance_6m  NUMERIC(18,2),
    credit_limit            NUMERIC(18,2),
    credit_utilization_pct  NUMERIC(6,2),
    overdraft_enabled       BOOLEAN      NOT NULL DEFAULT FALSE,
    card_type               VARCHAR(24),
    is_joint_account        BOOLEAN      NOT NULL DEFAULT FALSE,
    num_linked_devices      INTEGER,
    mobile_banking_enrolled BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_date         DATE,
    avg_monthly_txn_count   INTEGER,
    account_tier            VARCHAR(24),
    risk_rating             VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_acct_customer ON accounts (customer_id);

CREATE TABLE transactions (
    transaction_id          VARCHAR(40)  PRIMARY KEY,
    account_id              VARCHAR(32)  NOT NULL REFERENCES accounts (account_id),
    customer_id             VARCHAR(32)  NOT NULL REFERENCES customers (customer_id),
    txn_timestamp           TIMESTAMP    NOT NULL,
    direction               VARCHAR(8)   NOT NULL,          -- CREDIT | DEBIT
    amount                  NUMERIC(18,2) NOT NULL,
    currency                VARCHAR(3)   NOT NULL,
    -- Business rule 9: every amount normalised to the configured base currency
    -- so cross-currency patterns are comparable.
    amount_base             NUMERIC(18,2) NOT NULL,
    fx_rate_applied         NUMERIC(18,8) NOT NULL DEFAULT 1,
    channel                 VARCHAR(32),
    txn_type                VARCHAR(32),
    counterparty_name       VARCHAR(160),
    counterparty_account    VARCHAR(40),
    counterparty_bank       VARCHAR(120),
    counterparty_country    VARCHAR(2),
    description             VARCHAR(255),
    status                  VARCHAR(24)  NOT NULL DEFAULT 'POSTED',
    ingested_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Detection engine access paths: nearly every rule is a per-account or
-- per-customer time-window scan, so these two composite indexes carry the load.
CREATE INDEX idx_txn_acct_time ON transactions (account_id, txn_timestamp);
CREATE INDEX idx_txn_cust_time ON transactions (customer_id, txn_timestamp);
CREATE INDEX idx_txn_country   ON transactions (counterparty_country);

CREATE TABLE alerts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_ref               VARCHAR(40)  NOT NULL UNIQUE,
    customer_id             VARCHAR(32)  NOT NULL REFERENCES customers (customer_id),
    account_id              VARCHAR(32)  REFERENCES accounts (account_id),
    rule_code               VARCHAR(48)  NOT NULL,
    typology                VARCHAR(64)  NOT NULL,
    risk_score              INTEGER      NOT NULL,
    severity                VARCHAR(16)  NOT NULL,
    status                  VARCHAR(24)  NOT NULL DEFAULT 'OPEN',
    explanation             TEXT         NOT NULL,
    evidence_txn_ids        TEXT         NOT NULL,
    evidence_amount_base    NUMERIC(18,2),
    -- The components that produced risk_score, retained so the score is as
    -- auditable as the trigger (business rule 7 + explainability).
    score_breakdown         TEXT,
    -- Business rule: alert de-duplication. A deterministic key derived from
    -- (rule, account/customer, pattern window) - the UNIQUE constraint is what
    -- makes concurrent detection safe against duplicate alerts.
    dedup_key               VARCHAR(200) NOT NULL UNIQUE,
    trigger_count           INTEGER      NOT NULL DEFAULT 1,
    first_detected_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_detected_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Business rule 6: alerts are never deleted. Disposition is recorded here
    -- and the transition is additionally written to audit_log.
    disposition             VARCHAR(32),
    disposition_reason      TEXT,
    disposed_by             VARCHAR(80),
    disposed_at             TIMESTAMP,
    case_id                 BIGINT,
    version                 INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_alert_score  ON alerts (risk_score DESC);
CREATE INDEX idx_alert_status ON alerts (status);
CREATE INDEX idx_alert_cust   ON alerts (customer_id);
CREATE INDEX idx_alert_rule   ON alerts (rule_code);

CREATE TABLE cases (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_ref                VARCHAR(40)  NOT NULL UNIQUE,
    customer_id             VARCHAR(32)  NOT NULL REFERENCES customers (customer_id),
    title                   VARCHAR(200) NOT NULL,
    status                  VARCHAR(32)  NOT NULL DEFAULT 'NEW',
    priority                VARCHAR(16)  NOT NULL DEFAULT 'MEDIUM',
    aggregate_risk_score    INTEGER      NOT NULL DEFAULT 0,
    assigned_to             VARCHAR(80),
    narrative               TEXT,
    disposition             VARCHAR(32),
    disposition_reason      TEXT,
    opened_by               VARCHAR(80)  NOT NULL,
    opened_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at               TIMESTAMP,
    version                 INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_case_status ON cases (status);
CREATE INDEX idx_case_cust   ON cases (customer_id);

ALTER TABLE alerts ADD CONSTRAINT fk_alert_case FOREIGN KEY (case_id) REFERENCES cases (id);

-- ---------------------------------------------------------------------------
-- Immutable audit trail. Insert-only: no UPDATE/DELETE path exists in the
-- application layer, and every alert/case state transition writes a row here.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type             VARCHAR(32)  NOT NULL,
    entity_id               VARCHAR(40)  NOT NULL,
    action                  VARCHAR(48)  NOT NULL,
    actor                   VARCHAR(80)  NOT NULL,
    actor_roles             VARCHAR(160),
    from_state              VARCHAR(32),
    to_state                VARCHAR(32),
    details                 TEXT,
    occurred_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_time   ON audit_log (occurred_at DESC);

-- ---------------------------------------------------------------------------
-- Runtime-tunable rule configuration (no redeployment required).
-- params holds a JSON object of rule-specific thresholds / windows.
-- ---------------------------------------------------------------------------
CREATE TABLE rule_config (
    rule_code               VARCHAR(48)  PRIMARY KEY,
    name                    VARCHAR(120) NOT NULL,
    typology                VARCHAR(64)  NOT NULL,
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    weight                  INTEGER      NOT NULL,
    severity                VARCHAR(16)  NOT NULL DEFAULT 'MEDIUM',
    params                  TEXT         NOT NULL DEFAULT '{}',
    description             TEXT,
    updated_by              VARCHAR(80),
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                 INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE fx_rates (
    currency                VARCHAR(3)   PRIMARY KEY,
    rate_to_base            NUMERIC(18,8) NOT NULL,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE high_risk_jurisdictions (
    country_code            VARCHAR(2)   PRIMARY KEY,
    country_name            VARCHAR(80)  NOT NULL,
    category                VARCHAR(24)  NOT NULL,   -- SANCTIONED | HIGH_RISK | MONITORED
    risk_weight             INTEGER      NOT NULL DEFAULT 20,
    source                  VARCHAR(80),
    active                  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE watchlist_counterparties (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(160) NOT NULL,
    normalized_name         VARCHAR(160) NOT NULL,
    list_type               VARCHAR(32)  NOT NULL,
    country                 VARCHAR(2),
    notes                   VARCHAR(255),
    active                  BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_watchlist_norm ON watchlist_counterparties (normalized_name);

-- ---------------------------------------------------------------------------
-- Ingestion observability: every batch and every rejected row is recorded.
-- ---------------------------------------------------------------------------
CREATE TABLE ingestion_batch (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_ref               VARCHAR(40)  NOT NULL UNIQUE,
    entity_type             VARCHAR(32)  NOT NULL,
    source                  VARCHAR(160),
    total_records           INTEGER      NOT NULL DEFAULT 0,
    accepted_records        INTEGER      NOT NULL DEFAULT 0,
    rejected_records        INTEGER      NOT NULL DEFAULT 0,
    alerts_generated        INTEGER      NOT NULL DEFAULT 0,
    status                  VARCHAR(24)  NOT NULL DEFAULT 'RUNNING',
    started_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at             TIMESTAMP,
    duration_ms             BIGINT,
    initiated_by            VARCHAR(80)
);

CREATE TABLE ingestion_error (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                BIGINT       NOT NULL REFERENCES ingestion_batch (id),
    row_number              INTEGER      NOT NULL,
    record_key              VARCHAR(64),
    error_type              VARCHAR(48)  NOT NULL,
    error_message           VARCHAR(500) NOT NULL,
    raw_record              TEXT
);
CREATE INDEX idx_ingerr_batch ON ingestion_error (batch_id);
